---
- name: Gather Disk Information
  hosts: your_hosts
  gather_facts: yes
  tasks:
    - name: Display Disk Information
      debug:
        var: ansible_facts.devices
    - name:
      debug:
        var: ansible_facts.devices.keys()