#cloud-config
users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAEHCCQz560+fkq7kExTOt4CnLJOt7+R9IyxwW4WKIwn ubuntu@ip-172-31-41-30
  
#Update and install
package_update: true
package_upgrade: true